-- MySQL Script generated by MySQL Workbench
-- Sun Oct  2 19:24:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DripDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DripDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DripDatabase` DEFAULT CHARACTER SET utf8 ;
USE `DripDatabase` ;

-- -----------------------------------------------------
-- Table `DripDatabase`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DripDatabase`.`User` (
  `userID` INT NOT NULL,
  `userEmail` VARCHAR(255) NOT NULL,
  `profileName` VARCHAR(45) NOT NULL,
  `profileIconPath` NVARCHAR(260) NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DripDatabase`.`Outfit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DripDatabase`.`Outfit` (
  `outfitID` INT NOT NULL,
  `userCreatedID` INT NOT NULL,
  `mediaFilePath` NVARCHAR(260) NOT NULL,
  `createdDate` DATE NOT NULL,
  `outfitName` VARCHAR(45) NOT NULL,
  `lastWornDate` DATE NOT NULL,
  PRIMARY KEY (`outfitID`, `userCreatedID`),
  INDEX `fk_Outfit_User_idx` (`userCreatedID` ASC) VISIBLE,
  UNIQUE INDEX `userCreatedID_UNIQUE` (`userCreatedID` ASC) VISIBLE,
  UNIQUE INDEX `idOutfit_UNIQUE` (`outfitID` ASC) VISIBLE,
  CONSTRAINT `fk_Outfit_User`
    FOREIGN KEY (`userCreatedID`)
    REFERENCES `DripDatabase`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DripDatabase`.`wornDay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DripDatabase`.`wornDay` (
  `wornDayID` INT NOT NULL,
  `outfitID` INT NOT NULL,
  `dateWorn` DATE NULL,
  PRIMARY KEY (`wornDayID`, `outfitID`),
  INDEX `fk_wornDay_Outfit1_idx` (`outfitID` ASC) VISIBLE,
  CONSTRAINT `fk_wornDay_Outfit1`
    FOREIGN KEY (`outfitID`)
    REFERENCES `DripDatabase`.`Outfit` (`outfitID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DripDatabase`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DripDatabase`.`Post` (
  `postID` INT NOT NULL,
  `Outfit_outfitID` INT NOT NULL,
  `User_userID` INT NOT NULL,
  `postName` VARCHAR(45) NOT NULL,
  `numLikes` INT ZEROFILL UNSIGNED NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`postID`, `Outfit_outfitID`, `User_userID`),
  INDEX `fk_Post_Outfit1_idx` (`Outfit_outfitID` ASC) VISIBLE,
  INDEX `fk_Post_User1_idx` (`User_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Outfit1`
    FOREIGN KEY (`Outfit_outfitID`)
    REFERENCES `DripDatabase`.`Outfit` (`outfitID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `DripDatabase`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
